// src/app/constants/routes.ts
export const ROUTES = {
    home: '/',
    about: '/about',
    services: '/services',
    servicesRegular: '/services/regular',
    servicesPremium: '/services/premium',
    menu: '/menu',
    menuRegular: '/menu/regular',
    menuPremium: '/menu/premium',
    contact: '/contact',
    cart: '/cart',
    auth: '/auth',
    faqs: '/faqs',
    enquiry: '/enquiry',
    complaint: '/complaint',
    careers: '/careers',
    careersDelivery: '/careers/delivery',
    careersStudents: '/careers/students',
    partners: '/partners',
    partnersFarmers: '/partners/farmers',
    partnersDelivery: '/partners/delivery',
    planRegular: '/plan/regular',
    planPremium: '/plan/premium',
    dashboard: '/dashboard',
    privacyPolicy: '/privacy-policy',
    termsOfService: '/terms-of-service',
  };
  