[build]
  # Command to build the Next.js app
  command = "npm run build"
  # Directory to publish after building
  publish = ".next"
  # Path to Netlify edge functions
  edge_handlers = "netlify/edge-functions"

  # Environment variables for the build process
  [build.environment]
    NODE_ENV = "production"
    NEXT_PRIVATE_TARGET = "server"
    NEXT_PUBLIC_ENV = "true"
    CI = "false" # Disables CI mode to avoid stricter linting checks
    SKIP_TYPE_CHECK = "true" # Skip TypeScript type checking during the build

[dev]
  # Framework for local development
  framework = "next"

[[plugins]]
  # Netlify plugin for Next.js
  package = "@netlify/plugin-nextjs"

[[redirects]]
  # Redirect _next requests to ensure proper asset handling
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  force = true

[functions]
  # Customize Netlify function behavior
  node_bundler = "esbuild"
  included_files = ["src/**/*", "public/**/*"]
  directory = "netlify/functions"

# Additional processing options
[build.processing]
  skip_eslint = true
  skip_prettier = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
