[build]
  # Build command
  command = "npm run build"
  
  # Publish directory for the built site
  publish = ".next"
  
  # Edge handlers for Netlify functions
  edge_handlers = "netlify/edge-functions"
  
  # Environment variables to avoid common Next.js issues
  [build.environment]
    NODE_ENV = "production"
    NEXT_PRIVATE_TARGET = "server"
    NEXT_PUBLIC_ENV = "true"
    CI = "false" # Disable CI strictness for builds

[dev]
  # Framework setup for local development on Netlify
  framework = "next"

[[plugins]]
  # Using the official Next.js plugin for Netlify
  package = "@netlify/plugin-nextjs"

# Custom build behavior for ESLint, Prettier, and type-checking issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

[[redirects]]
  # Redirect requests to prevent runtime routing issues
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  force = true

[functions]
  # Set memory and timeout for server-side functions
  node_bundler = "esbuild"
  included_files = ["src/**/*", "public/**/*"]
  directory = "netlify/functions"

# Ignore ESLint errors during the build process
[build.processing]
  skip_eslint = true
  skip_prettier = true
